# Generated by Django 6.0.5 on 2026-06-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_team_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='role',
        ),
    ]
