# Generated by Django 6.0.5 on 2026-06-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_otpverification_email_alter_otpverification_user'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='otpverification',
            name='account_otp_user_id_c7256a_idx',
        ),
        migrations.RenameField(
            model_name='userlogdevice',
            old_name='device_token',
            new_name='device_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_device_info',
        ),
        migrations.AlterField(
            model_name='userlogdevice',
            name='device_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['email'], name='account_otp_email_428e64_idx'),
        ),
    ]
