# Generated by Django 6.0.5 on 2026-06-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_teammember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REMOVED', 'Removed'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20),
        ),
    ]
