# Generated by Django 6.0.5 on 2026-06-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_otpverification_account_otp_user_id_c7256a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
