# Generated by Django 6.0.5 on 2026-06-04 11:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_teammember_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REMOVED', 'Removed'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('show_popup', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('invite_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_team_invites', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='account.team')),
                ('team_member_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='account.teammember')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
