# Generated by Django 6.0.5 on 2026-06-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_teammemberinvite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammemberinvite',
            old_name='invite_by',
            new_name='invited_by',
        ),
    ]
