# Generated by Django 6.0.5 on 2026-06-04 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_invite_by_teammemberinvite_invited_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammemberinvite',
            old_name='invited_by',
            new_name='invited_to',
        ),
    ]
