# Generated by Django 6.0.5 on 2026-06-25 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_teammember_username_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
