# Generated by Django 6.0.6 on 2026-06-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammemberinvite',
            name='show_popup',
            field=models.BooleanField(default=True),
        ),
    ]
