# Generated by Django 6.0.6 on 2026-09-20 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor_company', models.CharField(db_index=True, max_length=255, verbose_name='Vendor / Company')),
                ('date_paid', models.DateField(db_index=True, verbose_name='Date Paid')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount ($)')),
                ('who_paid', models.CharField(max_length=255, verbose_name='Who Paid?')),
                ('payment_method', models.CharField(choices=[('MC Card', 'MC Card'), ('Visa', 'Visa'), ('Cash', 'Cash'), ('Wire', 'Wire'), ('Bank Transfer', 'Bank Transfer'), ('Other', 'Other')], default='MC Card', max_length=50, verbose_name='Payment Method')),
                ('recurring', models.CharField(choices=[('No', 'No'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='No', max_length=50, verbose_name='Recurring?')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date_paid', '-created_at'],
            },
        ),
    ]
