# Generated by Django 6.0.5 on 2026-06-03 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_teammember_role'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('PAST_DUE', 'Past Due'), ('FAILED', 'Failed'), ('TRIAL', 'Trial'), ('GRACE_PERIOD', 'Grace Period')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='account.team'),
        ),
    ]
