# Generated by Django 6.0.6 on 2026-06-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['-team_limit', 'billing_type', 'plan_type']},
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
