# Generated by Django 6.0.5 on 2026-06-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_usersubscription_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
