# Generated by Django 6.0.5 on 2026-06-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_usersubscription_cancelled_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='payment_status',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='grace_period_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=50),
        ),
    ]
