# Generated by Django 6.0.5 on 2026-06-03 13:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_rename_payment_status_paymenttransaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('REFUND_PROCESSING', 'Refund Processing'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('REFUND_PROCESSING', 'Refund Processing'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=50),
        ),
    ]
