# Generated by Django 6.0.5 on 2026-06-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_usersubscription_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='last_renew_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('REFUND_PROCESSING', 'Refund Processing'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='renewal_attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
