# Generated by Django 6.0.6 on 2026-09-20 04:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_number', models.CharField(blank=True, db_index=True, help_text='Format: RR-YYYY-00001', max_length=32, null=True, unique=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('OPEN', 'Open'), ('WAITING_CUSTOMER', 'Waiting for Customer'), ('WAITING_INTERNAL', 'Waiting for Internal Team'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('DRAFT', 'Draft')], db_index=True, default='NEW', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=20)),
                ('source', models.CharField(choices=[('WEBSITE_FORM', 'Website Support Form'), ('DASHBOARD', 'Ticket Creator in Dashboard'), ('STAFF_DISCOVERED', 'Staff-discovered'), ('AUTOMATED_ALERT', 'Automated system alert')], db_index=True, default='WEBSITE_FORM', max_length=40)),
                ('form_id', models.CharField(blank=True, max_length=50, null=True)),
                ('form_submission_id', models.CharField(blank=True, max_length=100, null=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(db_index=True, max_length=255)),
                ('customer_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('plan_type', models.CharField(blank=True, max_length=50, null=True)),
                ('main_category', models.CharField(choices=[('ACCOUNT_LOGIN', 'Account and Login Issues'), ('BILLING_SUBSCRIPTION', 'Billing and Subscription Issues'), ('PERMIT_PROCESSING', 'Permit Import and Processing'), ('ROUTE_NAVIGATION', 'Route and Navigation Issues'), ('APP_TECHNICAL', 'App Technical Issues'), ('TEAM_DRIVER', 'Team and Driver Management'), ('ACCOUNT_CHANGES', 'Account Changes and Requests'), ('COMPLAINT', 'Complaint or Service Concern'), ('FEATURE_REQUEST', 'Feature Request or Suggestion'), ('GENERAL_OTHER', 'General Question or Other')], db_index=True, max_length=50)),
                ('subcategory', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('safety_critical', models.BooleanField(default=False)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('device', models.CharField(blank=True, max_length=100, null=True)),
                ('app_version', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_contact_method', models.CharField(blank=True, choices=[('EMAIL', 'Email'), ('PHONE', 'Phone'), ('VIDEO_CALL', 'Video call'), ('WEBSITE_FORM', 'Website Form')], default='EMAIL', max_length=30, null=True)),
                ('assigned_name', models.CharField(blank=True, max_length=255, null=True)),
                ('send_confirmation_email', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('customer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_summary', models.CharField(max_length=500)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_activities', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='supports.supportticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='support_attachments/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='supports.supportticket')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_ticket_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('is_internal_note', models.BooleanField(default=False, help_text='If True, this is an internal note never sent to customer.')),
                ('is_system_note', models.BooleanField(default=False, help_text='If True, this message was auto-generated by the backend.')),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_ticket_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='supports.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status'], name='supports_su_status_f88e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['priority'], name='supports_su_priorit_8665c7_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['main_category'], name='supports_su_main_ca_513504_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['customer_email'], name='supports_su_custome_a966b1_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['archived_at'], name='supports_su_archive_cdae8b_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportticket',
            constraint=models.UniqueConstraint(condition=models.Q(('form_submission_id__isnull', False), models.Q(('form_submission_id', ''), _negated=True)), fields=('source', 'form_submission_id'), name='unique_support_ticket_submission'),
        ),
    ]
