# Generated by Django 6.0.6 on 2026-09-21 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_adminuserprofile'),
        ('supports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='account.team'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='source',
            field=models.CharField(choices=[('WEBSITE_FORM', 'Website Support Form'), ('TEAM_DASHBOARD', 'Team Dashboard Support Form'), ('DASHBOARD', 'Ticket Creator in Dashboard'), ('STAFF_DISCOVERED', 'Staff-discovered'), ('AUTOMATED_ALERT', 'Automated system alert')], db_index=True, default='WEBSITE_FORM', max_length=40),
        ),
        migrations.CreateModel(
            name='SupportResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='support_resources/')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, default='General', max_length=100, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_support_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
