# Generated by Django 6.0.5 on 2026-05-25 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('route_status', models.CharField(choices=[('DRAFT', 'Draft'), ('ON_GOING', 'On Going'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('ai_processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('total_distance_km', models.FloatField(default=0)),
                ('estimated_duration', models.PositiveIntegerField(default=0)),
                ('total_waypoints', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('route_progress_percentage', models.CharField(blank=True, max_length=255, null=True)),
                ('current_waypoint_index', models.CharField(blank=True, max_length=255, null=True)),
                ('is_rerouted', models.CharField(blank=True, max_length=255, null=True)),
                ('reroute_count', models.CharField(blank=True, max_length=255, null=True)),
                ('route_health_score', models.CharField(blank=True, max_length=255, null=True)),
                ('risk_score', models.CharField(blank=True, max_length=255, null=True)),
                ('compliance_score', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_summary', models.CharField(blank=True, max_length=255, null=True)),
                ('incident_detected', models.CharField(blank=True, max_length=255, null=True)),
                ('last_tracking_received_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='account.team')),
            ],
        ),
        migrations.CreateModel(
            name='RouteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='route.route')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoutePermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_location', models.CharField(blank=True, help_text='Start Location Name', max_length=255)),
                ('start_latitude', models.FloatField(help_text='Start location - Latitude')),
                ('start_longitude', models.FloatField(help_text='Start location - Longitude')),
                ('end_location', models.CharField(blank=True, help_text='End Location Name', max_length=255)),
                ('end_latitude', models.FloatField(help_text='End location - Latitude')),
                ('end_longitude', models.FloatField(help_text='End location - Longitude')),
                ('document', models.FileField(blank=True, help_text='Imported File (PDF/Image)', null=True, upload_to='permits/')),
                ('document_text', models.TextField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('ai_response_json', models.JSONField(default=dict)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('processing_started_at', models.DateTimeField()),
                ('processing_completed_at', models.DateTimeField()),
                ('processing_error', models.JSONField(default=dict)),
                ('confidence_score', models.CharField(default=50, max_length=20)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='route.route')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['route', 'index'],
            },
        ),
        migrations.CreateModel(
            name='PermitWaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(help_text="Waypoints Name (like as: 'Exit 340')", max_length=255)),
                ('waypoint_type', models.CharField(choices=[('START', 'Start'), ('STOP', 'Stop'), ('END', 'End'), ('CHECKPOINT', 'Checkpoint')], default='CHECKPOINT', max_length=20)),
                ('latitude', models.FloatField(help_text='Latitude')),
                ('longitude', models.FloatField(help_text='Longitude')),
                ('description', models.TextField(blank=True, help_text='Waypoint Details', null=True)),
                ('icon', models.CharField(default='📍', max_length=50)),
                ('eta_minutes', models.PositiveIntegerField(default=0)),
                ('metadata_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='route.routepermit')),
            ],
            options={
                'ordering': ['permit', 'index'],
            },
        ),
        migrations.CreateModel(
            name='RouteTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField()),
                ('speed', models.FloatField(default=0)),
                ('heading', models.FloatField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('tracked_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='route.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_tracking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['route_status'], name='route_route_route_s_3f3b1a_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['created_by'], name='route_route_created_6e5f6e_idx'),
        ),
        migrations.AddIndex(
            model_name='routepermit',
            index=models.Index(fields=['route', 'index'], name='route_route_route_i_1d3cc5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routepermit',
            unique_together={('route', 'index')},
        ),
        migrations.AddIndex(
            model_name='permitwaypoint',
            index=models.Index(fields=['permit', 'index'], name='route_permi_permit__de163e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='permitwaypoint',
            unique_together={('permit', 'index')},
        ),
        migrations.AddIndex(
            model_name='routetracking',
            index=models.Index(fields=['tracked_at'], name='route_route_tracked_e3a850_idx'),
        ),
    ]
