# Generated by Django 6.0.5 on 2026-06-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routepermit',
            name='uploaded_by',
        ),
        migrations.AlterField(
            model_name='route',
            name='last_tracking_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ON_GOING', 'On Going'), ('START', 'Start'), ('STOP', 'Stop'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
