# Generated by Django 6.0.5 on 2026-06-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_permitwaypoint_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permitwaypoint',
            name='metadata_json',
        ),
    ]
