# Generated by Django 6.0.5 on 2026-06-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_remove_routepermit_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
