# Generated by Django 6.0.5 on 2026-06-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_route_is_completed_route_is_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='routepermit',
            old_name='document',
            new_name='permit_file',
        ),
        migrations.RenameField(
            model_name='routepermit',
            old_name='document_text',
            new_name='permit_file_text',
        ),
    ]
