# Generated by Django 6.0.6 on 2026-07-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_remove_permitwaypoint_metadata_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
