# Generated by Django 6.0.5 on 2026-06-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_rename_title_route_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routepermit',
            name='processing_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routepermit',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
