# Generated by Django 6.0.5 on 2026-06-04 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0005_alter_routepermit_processing_completed_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routepermit',
            old_name='permit_file_text',
            new_name='permit_text',
        ),
    ]
