# Generated by Django 6.0.5 on 2026-06-06 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_invited_by_teammemberinvite_invited_to'),
        ('route', '0006_rename_permit_file_text_routepermit_permit_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='route',
            name='route_route_route_s_3f3b1a_idx',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='route_status',
            new_name='status',
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['status'], name='route_route_status_6c027e_idx'),
        ),
    ]
