# Generated by Django 6.0.6 on 2026-09-20 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProtectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.CharField(db_index=True, help_text='Auto-generated DR-YYYY-XXXX identifier.', max_length=20, unique=True)),
                ('date_requested', models.DateTimeField(help_text='When RightRoute received the request (defaults to now, admin-correctable).')),
                ('customer_email', models.EmailField(help_text='Email provided by the customer at time of request.', max_length=254)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('plan_type', models.CharField(blank=True, default='', max_length=50)),
                ('account_status', models.CharField(blank=True, default='', max_length=50)),
                ('account_created_at', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=50)),
                ('source', models.CharField(blank=True, choices=[('PHONE', 'Phone'), ('EMAIL', 'Email'), ('WRITTEN', 'Written Request'), ('OTHER', 'Other')], default='', max_length=20)),
                ('source_other_detail', models.CharField(blank=True, default='', help_text='Required when source=OTHER.', max_length=255)),
                ('request_type', models.CharField(blank=True, choices=[('EXPORT', 'Export User Data'), ('DELETE', 'Delete User Data'), ('ANONYMIZE', 'Anonymize User Data'), ('DELETE_ANONYMIZE', 'Delete and Anonymize Retained Data')], default='', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PENDING_APPROVAL', 'Pending Approval'), ('COMPLETED', 'Completed')], db_index=True, default='NEW', max_length=20)),
                ('approval_received', models.BooleanField(default=False, help_text='Customer replied confirming the requested action.')),
                ('approval_source', models.CharField(blank=True, default='', help_text='How the approval arrived (email, phone, letter, etc.).', max_length=255)),
                ('approval_received_date', models.DateField(blank=True, help_text="Date admin received the customer's approval.", null=True)),
                ('admin_confirmed', models.BooleanField(default=False, help_text='Admin has confirmed: approval came from a verified email; the action is correct; and, for deletion/anonymization, the action may be irreversible.')),
                ('approval_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(blank=True, help_text='Timestamp when the backend process was triggered.', null=True)),
                ('perform_result', models.TextField(blank=True, default='', help_text='System-generated summary of what was done during perform.')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('export_zip_path', models.CharField(blank=True, default='', help_text='Relative path to the generated ZIP file in protected storage.', max_length=500)),
                ('export_zip_size', models.BigIntegerField(blank=True, help_text='File size in bytes.', null=True)),
                ('export_zip_created_at', models.DateTimeField(blank=True, null=True)),
                ('export_zip_expires_at', models.DateTimeField(blank=True, help_text='Download link expires after 7 days.', null=True)),
                ('export_download_token', models.CharField(blank=True, help_text='Secure token used in the download URL; revocable by RightRoute.', max_length=100, null=True, unique=True)),
                ('approval_email_sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_approval_emails', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_data_requests', to=settings.AUTH_USER_MODEL)),
                ('customer_user', models.ForeignKey(blank=True, help_text='Linked RightRoute account (resolved via FIND button).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_protection_requests', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_data_requests', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_data_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Protection Request',
                'verbose_name_plural': 'Data Protection Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRequestNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_system_note', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='security.dataprotectionrequest')),
                ('written_by', models.ForeignKey(blank=True, help_text='Null for system-generated notes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_request_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Request Note',
                'verbose_name_plural': 'Data Request Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dataprotectionrequest',
            index=models.Index(fields=['status'], name='security_da_status_2536b7_idx'),
        ),
        migrations.AddIndex(
            model_name='dataprotectionrequest',
            index=models.Index(fields=['customer_email'], name='security_da_custome_d2522a_idx'),
        ),
        migrations.AddIndex(
            model_name='dataprotectionrequest',
            index=models.Index(fields=['request_id'], name='security_da_request_5d09cd_idx'),
        ),
    ]
