# Generated by Django 6.0.6 on 2026-09-22 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_adminuserprofile'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprotectionrequest',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Linked Team for team-submitted requests.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_protection_requests', to='account.team'),
        ),
        migrations.AlterField(
            model_name='dataprotectionrequest',
            name='source',
            field=models.CharField(blank=True, choices=[('PHONE', 'Phone'), ('EMAIL', 'Email'), ('WRITTEN', 'Written Request'), ('TEAM_DASHBOARD', 'Team Dashboard'), ('OTHER', 'Other')], default='', max_length=20),
        ),
    ]
