# Generated by Django 6.0.6 on 2026-09-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamadminprofile',
            name='role_label',
            field=models.CharField(blank=True, help_text="Custom role label displayed in UI (e.g. 'Legal Adviser', 'Super Admin')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teamadminprofile',
            name='user_id_display',
            field=models.CharField(blank=True, help_text="Display User ID (e.g. 'USR-1082')", max_length=20, null=True, unique=True),
        ),
    ]
